#!/bin/sh


mkdir -p /var/mobile/Library/SuccessorCLI
echo 'SuccessorCLI Credits go to the following people:\nDabezt, for creating this program\nSamgisaninja, for creating the original Succession program, of which this is a based of\nAmy While, for providing a Swift wrapper to libzip (although thats not used anymore)'
